### ISSUE TITLE
Failed to install: node-red-contrib-image-tools  Install failed

### ISSUE THREAD

**Issue by TCB922** [Steve-Mcl/node-red-contrib-image-tools#46]
Trying to install and no luck! 

Here are two logs - The error install log and the container log - any help please

-----------------------------------------------------------
2024-02-28T17:43:39.387Z Install : node-red-contrib-image-tools 2.1.0

2024-02-28T17:44:02.386Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-image-tools@2.1.0
2024-02-28T17:44:02.950Z [err] npm
2024-02-28T17:44:02.950Z [err]  WARN
2024-02-28T17:44:02.950Z [err]  config production Use `--omit=dev` instead.
2024-02-28T17:44:23.096Z [err] npm 
2024-02-28T17:44:23.096Z [err] ERR! code ETARGET
2024-02-28T17:44:23.100Z [err] npm ERR!
2024-02-28T17:44:23.100Z [err]  notarget No matching version found for bwip-js@^4.20.
2024-02-28T17:44:23.100Z [err] npm ERR!
2024-02-28T17:44:23.100Z [err]  notarget In most cases you or one of your dependencies are requesting
2024-02-28T17:44:23.100Z [err] npm ERR! 
2024-02-28T17:44:23.100Z [err] notarget a package version that doesn't exist.
2024-02-28T17:44:23.103Z [err] 
2024-02-28T17:44:23.103Z [err] npm 
2024-02-28T17:44:23.103Z [err] ERR! A complete log of this run can be found in:
2024-02-28T17:44:23.103Z [err] npm 
2024-02-28T17:44:23.104Z [err] ERR!     /data/.npm/_logs/2024-02-28T17_44_02_907Z-debug-0.log
2024-02-28T17:44:23.124Z rc=1

And here is the log from the container:
28 Feb 17:35:13 - [info] Installing module: node-red-contrib-image-tools, version: 2.1.0
28 Feb 17:35:34 - [warn] Installation of module node-red-contrib-image-tools failed:
28 Feb 17:35:34 - [warn] ------------------------------------------
28 Feb 17:35:34 - [warn] npm WARN config production Use `--omit=dev` instead.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for bwip-js@^4.20.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR!     /data/.npm/_logs/2024-02-28T17_35_15_268Z-debug-0.log
28 Feb 17:35:34 - [warn] ------------------------------------------
Error: Install failed
    at /usr/src/node-red/node_modules/@node-red/registry/lib/installer.js:285:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
28 Feb 17:35:34 - [error] Error: Install failed
28 Feb 17:39:17 - [info] Installing module: node-red-contrib-image-tools, version: 2.1.0
28 Feb 17:39:19 - [warn] Installation of module node-red-contrib-image-tools failed:
28 Feb 17:39:19 - [warn] ------------------------------------------
28 Feb 17:39:19 - [warn] npm WARN config production Use `--omit=dev` instead.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for bwip-js@^4.20.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR!     /data/.npm/_logs/2024-02-28T17_39_18_370Z-debug-0.log
28 Feb 17:39:19 - [warn] ------------------------------------------
Error: Install failed
    at /usr/src/node-red/node_modules/@node-red/registry/lib/installer.js:285:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
28 Feb 17:39:19 - [error] Error: Install failed
28 Feb 17:44:02 - [info] Installing module: node-red-contrib-image-tools, version: 2.1.0
28 Feb 17:44:23 - [warn] Installation of module node-red-contrib-image-tools failed:

**Comment by Steve-Mcl** [comment]
Oh dear, looks like a dependency typo. Oddly it worked on my development machine. Will get back to you shortly.

**Comment by Steve-Mcl** [comment]
duplicate #46

**Comment by Steve-Mcl** [comment]
node-red library updated to v2.1.1 - it can take up to 30 mins to populate the node-red catalog (use `npm install node-red-contrib-image-tools@latest` to get the update quicker)
